#!/usr/bin/env python3
"""Generate the name -> function table that resolves cimgui exports in browser-wasm.

Mono on browser-wasm has no dynamic symbol lookup: NativeLibrary.GetExport only finds
functions that some assembly declares with [DllImport]. The binding instead calls the single
DllImport `cimgui_wasm_get_proc_address`, which searches this table.

Usage: gen_cimgui_exports.py <cimgui.h> <nm-output> <out.c>

Only functions both declared in cimgui.h and defined in the compiled archive (per llvm-nm) are
listed, so preprocessor-disabled declarations (backends, freetype) cannot reach the table.
The generated file includes cimgui.h, so every address is taken through its real prototype;
wasm-ld would otherwise emit trapping signature-mismatch stubs.
"""

import re
import sys

DECLARATION = re.compile(r"^CIMGUI_API\b[^(]*?\b([A-Za-z_]\w*)\s*\(", re.MULTILINE)


def main() -> None:
    header_path, nm_path, out_path = sys.argv[1:4]
    with open(header_path, encoding="utf-8") as header:
        declared = set(DECLARATION.findall(header.read()))

    defined = set()
    with open(nm_path, encoding="utf-8") as nm:
        for line in nm:
            parts = line.split()
            # llvm-nm lines: "<address> <type> <name>"; T marks a defined function.
            if len(parts) == 3 and parts[1] == "T":
                defined.add(parts[2])

    names = sorted(declared & defined)
    if not names:
        sys.exit("no cimgui exports found; check the header and nm output")

    # bsearch uses strcmp, so the table must be in byte order; ASCII names sort identically.
    entries = "\n".join(f'    {{"{name}", (void*){name}}},' for name in names)
    with open(out_path, "w", encoding="utf-8", newline="\n") as out:
        out.write(f"""// Generated by scripts/wasm/gen_cimgui_exports.py. Do not edit.
#define CIMGUI_DEFINE_ENUMS_AND_STRUCTS
#include "cimgui.h"
#include <stdlib.h>
#include <string.h>

typedef struct cimgui_export
{{
    const char* name;
    void* proc;
}} cimgui_export;

static const cimgui_export s_exports[] =
{{
{entries}
}};

static int compare_export(const void* key, const void* entry)
{{
    return strcmp((const char*)key, ((const cimgui_export*)entry)->name);
}}

void* cimgui_wasm_get_proc_address(const char* name)
{{
    const cimgui_export* found = (const cimgui_export*)bsearch(
        name, s_exports, sizeof(s_exports) / sizeof(s_exports[0]), sizeof(s_exports[0]), compare_export);
    return found ? found->proc : NULL;
}}
""")
    print(f"{len(names)} exports ({len(declared)} declared, {len(defined)} defined)")


if __name__ == "__main__":
    main()
