// Generates Browser/InterpToNativeSignatures.cs for a compiled binding assembly.
//
// Usage: dotnet run scripts/wasm/GenerateInterpToNativeSignatures.cs -- <Binding.dll> <namespace> <out.cs>
//
// Mono's interpreter on browser-wasm calls native function pointers through trampolines that
// are generated at app build time, one per signature, and aborts on a calli whose signature has
// none (aot-runtime-wasm.c). The WasmAppBuilder only collects signatures from [DllImport]
// methods and [UnmanagedFunctionPointer] delegates, never from calli sites, so every unmanaged
// calli signature in the binding is declared here as such a delegate. The type mapping mirrors
// dotnet/runtime src/tasks/WasmAppBuilder/SignatureMapper.cs.
using System.Collections.Immutable;
using System.Reflection.Metadata;
using System.Reflection.Metadata.Ecma335;
using System.Reflection.PortableExecutable;
using System.Text;

if (args.Length != 3)
{
    Console.Error.WriteLine("usage: GenerateInterpToNativeSignatures.cs <Binding.dll> <namespace> <out.cs>");
    return 1;
}

using var stream = File.OpenRead(args[0]);
using var pe = new PEReader(stream);
MetadataReader metadata = pe.GetMetadataReader();
var provider = new SignatureCharProvider(metadata);
var signatures = new SortedSet<string>(StringComparer.Ordinal);

foreach (MethodDefinitionHandle handle in metadata.MethodDefinitions)
{
    MethodDefinition method = metadata.GetMethodDefinition(handle);
    if (method.RelativeVirtualAddress == 0)
    {
        continue;
    }
    MethodBodyBlock body = pe.GetMethodBody(method.RelativeVirtualAddress);
    foreach (StandaloneSignatureHandle calli in CalliSignatures(body.GetILReader()))
    {
        StandaloneSignature standalone = metadata.GetStandaloneSignature(calli);
        MethodSignature<string> signature = standalone.DecodeMethodSignature(provider, genericContext: null);
        if (signature.Header.CallingConvention is SignatureCallingConvention.Default or SignatureCallingConvention.VarArgs)
        {
            continue; // managed calli, not a native call
        }
        signatures.Add(ToCookie(signature));
    }
}

var source = new StringBuilder();
source.Append($$"""
    // <auto-generated>
    //     Generated by scripts/wasm/GenerateInterpToNativeSignatures.cs. Do not edit.
    // </auto-generated>
    #if NET5_0_OR_GREATER
    namespace {{args[1]}}
    {
        using System.Diagnostics.CodeAnalysis;
        using System.Runtime.InteropServices;

        /// <summary>One delegate per native call signature the binding uses, named by its Mono wasm signature cookie.</summary>
        /// <remarks>Never invoked. Their presence makes the wasm app build generate the interpreter-to-native trampolines that calls through the binding's function pointers need.</remarks>
        internal static class InterpToNativeSignatures
        {

    """);
foreach (string cookie in signatures)
{
    string returnType = NativeType(cookie[0]);
    string parameters = string.Join(", ", cookie.Skip(1).Select((c, i) => $"{NativeType(c)} a{i}"));
    source.Append($"        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate {returnType} {cookie}({parameters});\n");
}
source.Append("""

            /// <summary>Keeps every signature delegate through trimming; the wasm build scans the trimmed assemblies.</summary>

    """);
foreach (string cookie in signatures)
{
    source.Append($"        [DynamicDependency(\"Invoke\", typeof({cookie}))]\n");
}
source.Append("""
            internal static void Keep()
            {
            }
        }
    }
    #endif

    """);
File.WriteAllText(args[2], source.ToString().ReplaceLineEndings("\n"));
Console.WriteLine($"{signatures.Count} signatures -> {args[2]}");
return 0;

// Struct results travel through a pointer in slot 0 (sret), which is what the runtime's "VI" prefix encodes.
static string ToCookie(MethodSignature<string> signature)
{
    string result = signature.ReturnType == "S" ? "VI" : signature.ReturnType;
    return result + string.Concat(signature.ParameterTypes.Select(p => p == "S" ? "I" : p));
}

static string NativeType(char c) => c switch
{
    'V' => "void",
    'I' => "int",
    'L' => "long",
    'F' => "float",
    'D' => "double",
    _ => throw new InvalidOperationException($"unknown signature char '{c}'"),
};

static IEnumerable<StandaloneSignatureHandle> CalliSignatures(BlobReader il)
{
    var found = new List<StandaloneSignatureHandle>();
    while (il.RemainingBytes > 0)
    {
        int code = il.ReadByte();
        if (code == 0xFE)
        {
            code = 0xFE00 | il.ReadByte();
        }
        if (code == 0x29) // calli
        {
            found.Add(MetadataTokens.StandaloneSignatureHandle(il.ReadInt32() & 0xFFFFFF));
            continue;
        }
        il.Offset += OperandSize(code, ref il);
    }
    return found;
}

static int OperandSize(int code, ref BlobReader il)
{
    switch (code)
    {
        case 0x45: // switch
            int count = il.ReadInt32();
            return count * 4;
        case >= 0x0E and <= 0x13: // ldarg.s .. stloc.s
        case 0x1F: // ldc.i4.s
        case >= 0x2B and <= 0x37: // short branches
        case 0xDE: // leave.s
        case 0xFE12: // unaligned.
        case 0xFE19: // no.
            return 1;
        case >= 0xFE09 and <= 0xFE0E: // ldarg .. stloc
            return 2;
        case 0x20: // ldc.i4
        case 0x22: // ldc.r4
        case >= 0x38 and <= 0x44: // long branches
        case 0xDD: // leave
        case >= 0x27 and <= 0x29: // jmp, call, calli
        case >= 0x6F and <= 0x75: // callvirt, cpobj, ldobj, ldstr, newobj, castclass, isinst
        case 0x79: // unbox
        case >= 0x7B and <= 0x81: // ldfld .. stobj
        case 0x8C: // box
        case 0x8D: // newarr
        case 0x8F: // ldelema
        case >= 0xA3 and <= 0xA5: // ldelem, stelem, unbox.any
        case 0xC2: // refanyval
        case 0xC6: // mkrefany
        case 0xD0: // ldtoken
        case 0xFE06: // ldftn
        case 0xFE07: // ldvirtftn
        case 0xFE15: // initobj
        case 0xFE16: // constrained.
        case 0xFE1C: // sizeof
            return 4;
        case 0x21: // ldc.i8
        case 0x23: // ldc.r8
            return 8;
        default:
            return 0;
    }
}

/// <summary>Maps types to SignatureMapper characters; "S" marks a struct passed or returned through a pointer.</summary>
sealed class SignatureCharProvider(MetadataReader metadata) : ISignatureTypeProvider<string, object?>
{
    public string GetPrimitiveType(PrimitiveTypeCode typeCode) => typeCode switch
    {
        PrimitiveTypeCode.Void => "V",
        PrimitiveTypeCode.Int64 or PrimitiveTypeCode.UInt64 => "L",
        PrimitiveTypeCode.Single => "F",
        PrimitiveTypeCode.Double => "D",
        _ => "I",
    };

    public string GetPointerType(string elementType) => "I";
    public string GetByReferenceType(string elementType) => "I";
    public string GetFunctionPointerType(MethodSignature<string> signature) => "I";
    public string GetSZArrayType(string elementType) => "I";
    public string GetArrayType(string elementType, ArrayShape shape) => "I";
    public string GetPinnedType(string elementType) => elementType;
    public string GetModifiedType(string modifier, string unmodifiedType, bool isRequired) => unmodifiedType;
    public string GetGenericInstantiation(string genericType, ImmutableArray<string> typeArguments) =>
        genericType == "S" ? "S" : genericType;
    public string GetGenericMethodParameter(object? genericContext, int index) => throw new NotSupportedException("generic calli");
    public string GetGenericTypeParameter(object? genericContext, int index) => throw new NotSupportedException("generic calli");
    public string GetSentinelType() => throw new NotSupportedException("vararg calli");

    public string GetTypeFromDefinition(MetadataReader reader, TypeDefinitionHandle handle, byte rawTypeKind)
    {
        if (rawTypeKind != (byte)SignatureTypeKind.ValueType)
        {
            return "I";
        }
        TypeDefinition type = reader.GetTypeDefinition(handle);
        var fields = type.GetFields()
            .Select(reader.GetFieldDefinition)
            .Where(f => (f.Attributes & System.Reflection.FieldAttributes.Static) == 0)
            .ToList();
        // Enums have one instance field, value__, so they map to their underlying type too.
        return fields.Count == 1 ? fields[0].DecodeSignature(this, null) : "S";
    }

    public string GetTypeFromReference(MetadataReader reader, TypeReferenceHandle handle, byte rawTypeKind)
    {
        if (rawTypeKind != (byte)SignatureTypeKind.ValueType)
        {
            return "I";
        }
        TypeReference type = reader.GetTypeReference(handle);
        string name = $"{reader.GetString(type.Namespace)}.{reader.GetString(type.Name)}";
        return name switch
        {
            "System.IntPtr" or "System.UIntPtr" or "System.Boolean" or "System.Char" => "I",
            "System.Numerics.Vector2" or "System.Numerics.Vector3" or "System.Numerics.Vector4"
                or "System.Numerics.Quaternion" or "System.Numerics.Matrix3x2" or "System.Numerics.Matrix4x4" => "S",
            // HexaGen.Runtime wrappers, by their instance fields.
            "HexaGen.Runtime.Pointer`1" or "HexaGen.Runtime.ConstPointer`1"
                or "HexaGen.Runtime.Bool8" or "HexaGen.Runtime.Bool32" => "I",
            "HexaGen.Runtime.Atomic`1" => "L",
            "HexaGen.Runtime.Iterator`1" or "HexaGen.Runtime.NativeCallback`1" => "S",
            _ => throw new NotSupportedException($"value type '{name}' from another assembly in a calli signature"),
        };
    }

    public string GetTypeFromSpecification(MetadataReader reader, object? genericContext, TypeSpecificationHandle handle, byte rawTypeKind) =>
        reader.GetTypeSpecification(handle).DecodeSignature(this, genericContext);
}
