namespace Generator.Targets
{
    using Generator.Wasm;
    using HexaGen.BuildSystems;
    using HexaGen.Metadata;
    using System.Collections.Generic;
    using System.Text;

    public static class WasmTargetExtensions
    {
        public static BuildSystemBuilder AddWasm(this BuildSystemBuilder builder)
        {
            builder.AddTarget<WasmTarget>();
            return builder;
        }
    }

    /// <summary>
    /// Generates the browser-wasm glue for Hexa.NET.ImGui from the imgui target's metadata.
    /// </summary>
    /// <remarks>
    /// Mono on browser-wasm links natives statically into dotnet.wasm and resolves only [DllImport] symbols, and its interpreter
    /// calls function pointers only through trampolines generated at app build time from [DllImport] and
    /// [UnmanagedFunctionPointer] signatures. So the function table needs two generated files:
    /// <list type="bullet">
    /// <item>cimgui_wasm_exports.c: a name table behind <c>cimgui_wasm_get_proc_address</c>, compiled into cimgui.a by
    /// scripts/build_cimgui_wasm.sh and used by BrowserNativeContext;</item>
    /// <item>InterpToNativeSignatures.cs: one [UnmanagedFunctionPointer] delegate per distinct native signature.</item>
    /// </list>
    /// </remarks>
    public class WasmTarget : ImGuiBaseTarget
    {
        private const string OutputPath = "../../../../Hexa.NET.ImGui/Browser";
        private const string Namespace = "Hexa.NET.ImGui";

        public override string Name { get; } = "wasm";

        public override IReadOnlyList<string> Dependencies { get; } = ["imgui"];

        public override void Execute(BuildContext context)
        {
            CsCodeGeneratorMetadata metadata = GetImGuiMetadata(context);
            var signatures = metadata.GetEntry<MetadataDictionaryEntry<string, string>>(WasmSignatureGenerationStep.MetadataKey)
                ?? throw new InvalidOperationException($"imgui metadata has no '{WasmSignatureGenerationStep.MetadataKey}' entry.");

            List<string> exports = metadata.FunctionTable.Entries.Select(e => e.EntryPoint).Distinct().Order(StringComparer.Ordinal).ToList();
            SortedSet<string> cookies = new(StringComparer.Ordinal);
            foreach (string export in exports)
            {
                if (!signatures.TryGetValue(export, out string? cookie))
                {
                    throw new InvalidOperationException($"function table entry '{export}' has no recorded native signature.");
                }
                cookies.Add(cookie);
            }

            Directory.CreateDirectory(OutputPath);
            Write(Path.Combine(OutputPath, "cimgui_wasm_exports.c"), GenerateExportTable(exports));
            Write(Path.Combine(OutputPath, "InterpToNativeSignatures.cs"), GenerateSignatures(cookies));
            Console.WriteLine($"wasm: {exports.Count} exports, {cookies.Count} native signatures");
        }

        private static void Write(string path, string content)
        {
            File.WriteAllText(path, content.ReplaceLineEndings("\n"));
        }

        private static string GenerateExportTable(List<string> exports)
        {
            StringBuilder sb = new();
            sb.Append("""
                // <auto-generated>
                //     Generated by Generator/Targets/WasmTarget.cs from the binding's function table. Do not edit.
                // </auto-generated>
                // Includes cimgui.h so every address is taken through its real prototype; wasm-ld would otherwise emit trapping
                // signature-mismatch stubs. Compile with the defines the archive is built with (IMGUI_ENABLE_FREETYPE etc.).
                #define CIMGUI_DEFINE_ENUMS_AND_STRUCTS
                #include "cimgui.h"
                #include <stdlib.h>
                #include <string.h>

                typedef struct cimgui_export
                {
                    const char* name;
                    void* proc;
                } cimgui_export;

                // Sorted by strcmp order for bsearch.
                static const cimgui_export s_exports[] =
                {

                """);
            foreach (string export in exports)
            {
                sb.Append($"    {{\"{export}\", (void*){export}}},\n");
            }
            sb.Append("""
                };

                static int compare_export(const void* key, const void* entry)
                {
                    return strcmp((const char*)key, ((const cimgui_export*)entry)->name);
                }

                void* cimgui_wasm_get_proc_address(const char* name)
                {
                    const cimgui_export* found = (const cimgui_export*)bsearch(
                        name, s_exports, sizeof(s_exports) / sizeof(s_exports[0]), sizeof(s_exports[0]), compare_export);
                    return found ? found->proc : NULL;
                }

                """);
            return sb.ToString();
        }

        private static string GenerateSignatures(SortedSet<string> cookies)
        {
            StringBuilder sb = new();
            sb.Append($$"""
                // <auto-generated>
                //     Generated by Generator/Targets/WasmTarget.cs from the binding's function table. Do not edit.
                // </auto-generated>
                #if NET5_0_OR_GREATER
                namespace {{Namespace}}
                {
                    using System.Diagnostics.CodeAnalysis;
                    using System.Runtime.InteropServices;

                    /// <summary>One delegate per native call signature the binding uses, named by its Mono wasm signature cookie.</summary>
                    /// <remarks>Never invoked. Their presence makes the wasm app build generate the interpreter-to-native trampolines that calls through the binding's function pointers need.</remarks>
                    internal static class InterpToNativeSignatures
                    {

                """);
            foreach (string cookie in cookies)
            {
                string parameters = string.Join(", ", cookie.Skip(1).Select((c, i) => $"{NativeType(c)} a{i}"));
                sb.Append($"        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate {NativeType(cookie[0])} {cookie}({parameters});\n");
            }
            sb.Append("""

                        /// <summary>Keeps every signature delegate through trimming; the wasm build scans the trimmed assemblies.</summary>

                """);
            foreach (string cookie in cookies)
            {
                sb.Append($"        [DynamicDependency(\"Invoke\", typeof({cookie}))]\n");
            }
            sb.Append("""
                        internal static void Keep()
                        {
                        }
                    }
                }
                #endif

                """);
            return sb.ToString();
        }

        private static string NativeType(char c) => c switch
        {
            'V' => "void",
            'I' => "int",
            'L' => "long",
            'F' => "float",
            'D' => "double",
            _ => throw new InvalidOperationException($"unknown signature char '{c}'"),
        };
    }
}
