// <auto-generated>
//     Generated by Generator/Targets/WasmTarget.cs from the binding's function table. Do not edit.
// </auto-generated>
#if NET5_0_OR_GREATER
namespace Hexa.NET.ImGui
{
    using System.Diagnostics.CodeAnalysis;
    using System.Runtime.InteropServices;

    /// <summary>One delegate per native call signature the binding uses, named by its Mono wasm signature cookie.</summary>
    /// <remarks>Never invoked. Their presence makes the wasm app build generate the interpreter-to-native trampolines that calls through the binding's function pointers need.</remarks>
    internal static class InterpToNativeSignatures
    {
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate double D();
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate double DD(double a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate double DDD(double a0, double a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate float F();
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate float FF(float a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate float FFF(float a0, float a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate float FFFF(float a0, float a1, float a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate float FFFFFF(float a0, float a1, float a2, float a3, float a4);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate float FFFI(float a0, float a1, int a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate float FI(int a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate float FIF(int a0, float a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate float FIFFFF(int a0, float a1, float a2, float a3, float a4);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate float FII(int a0, int a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate float FIIF(int a0, int a1, float a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate float FIII(int a0, int a1, int a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int I();
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IF(float a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IFF(float a0, float a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IFFFF(float a0, float a1, float a2, float a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int II(int a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIF(int a0, float a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIFF(int a0, float a1, float a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIFIIF(int a0, float a1, int a2, int a3, float a4);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIFIIFI(int a0, float a1, int a2, int a3, float a4, int a5);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int III(int a0, int a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIDDII(int a0, int a1, double a2, double a3, int a4, int a5);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIF(int a0, int a1, float a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIFF(int a0, int a1, float a2, float a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIFFFII(int a0, int a1, float a2, float a3, float a4, int a5, int a6);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIFFI(int a0, int a1, float a2, float a3, int a4);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIFFII(int a0, int a1, float a2, float a3, int a4, int a5);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIFII(int a0, int a1, float a2, int a3, int a4);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIFIIII(int a0, int a1, float a2, int a3, int a4, int a5, int a6);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIII(int a0, int a1, int a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIIFFFIII(int a0, int a1, int a2, float a3, float a4, float a5, int a6, int a7, int a8);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIIFFII(int a0, int a1, int a2, float a3, float a4, int a5, int a6);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIIFI(int a0, int a1, int a2, float a3, int a4);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIIFII(int a0, int a1, int a2, float a3, int a4, int a5);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIIFIIII(int a0, int a1, int a2, float a3, int a4, int a5, int a6, int a7);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIIFIIIII(int a0, int a1, int a2, float a3, int a4, int a5, int a6, int a7, int a8);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIII(int a0, int a1, int a2, int a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIIIF(int a0, int a1, int a2, int a3, float a4);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIIIFIIII(int a0, int a1, int a2, int a3, float a4, int a5, int a6, int a7, int a8);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIIII(int a0, int a1, int a2, int a3, int a4);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIIIIF(int a0, int a1, int a2, int a3, int a4, float a5);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIIIIFFFFI(int a0, int a1, int a2, int a3, int a4, float a5, float a6, float a7, float a8, int a9);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIIIII(int a0, int a1, int a2, int a3, int a4, int a5);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIIIIII(int a0, int a1, int a2, int a3, int a4, int a5, int a6);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIIIIIIFFI(int a0, int a1, int a2, int a3, int a4, int a5, int a6, float a7, float a8, int a9);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIIIIIII(int a0, int a1, int a2, int a3, int a4, int a5, int a6, int a7);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIIIIIIII(int a0, int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIIILLI(int a0, int a1, int a2, int a3, long a4, long a5, int a6);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IIIL(int a0, int a1, long a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate int IL(long a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate long LI(int a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate long LILLI(int a0, long a1, long a2, int a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate long LL(long a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void V();
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VF(float a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VFF(float a0, float a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VFFFIII(float a0, float a1, float a2, int a3, int a4, int a5);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VFFI(float a0, float a1, int a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VFFII(float a0, float a1, int a2, int a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VFII(float a0, int a1, int a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VI(int a0);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIF(int a0, float a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIFF(int a0, float a1, float a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIFFFF(int a0, float a1, float a2, float a3, float a4);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIFFFIF(int a0, float a1, float a2, float a3, int a4, float a5);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIFFII(int a0, float a1, float a2, int a3, int a4);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIFI(int a0, float a1, int a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIFIIII(int a0, float a1, int a2, int a3, int a4, int a5);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VII(int a0, int a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIF(int a0, int a1, float a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIFF(int a0, int a1, float a2, float a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIFFFI(int a0, int a1, float a2, float a3, float a4, int a5);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIFFFIII(int a0, int a1, float a2, float a3, float a4, int a5, int a6, int a7);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIFFFIIIIII(int a0, int a1, float a2, float a3, float a4, int a5, int a6, int a7, int a8, int a9, int a10);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIFI(int a0, int a1, float a2, int a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIFII(int a0, int a1, float a2, int a3, int a4);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIFIIF(int a0, int a1, float a2, int a3, int a4, float a5);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIFIII(int a0, int a1, float a2, int a3, int a4, int a5);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIFIIII(int a0, int a1, float a2, int a3, int a4, int a5, int a6);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIFIIIIFI(int a0, int a1, float a2, int a3, int a4, int a5, int a6, float a7, int a8);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIFIIIIIFI(int a0, int a1, float a2, int a3, int a4, int a5, int a6, int a7, float a8, int a9);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIII(int a0, int a1, int a2);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIF(int a0, int a1, int a2, float a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIFFF(int a0, int a1, int a2, float a3, float a4, float a5);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIFFFI(int a0, int a1, int a2, float a3, float a4, float a5, int a6);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIFI(int a0, int a1, int a2, float a3, int a4);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIFIII(int a0, int a1, int a2, float a3, int a4, int a5, int a6);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIII(int a0, int a1, int a2, int a3);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIIF(int a0, int a1, int a2, int a3, float a4);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIIFFI(int a0, int a1, int a2, int a3, float a4, float a5, int a6);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIIFI(int a0, int a1, int a2, int a3, float a4, int a5);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIIFIF(int a0, int a1, int a2, int a3, float a4, int a5, float a6);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIIFIFI(int a0, int a1, int a2, int a3, float a4, int a5, float a6, int a7);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIII(int a0, int a1, int a2, int a3, int a4);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIIIF(int a0, int a1, int a2, int a3, int a4, float a5);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIIIFFII(int a0, int a1, int a2, int a3, int a4, float a5, float a6, int a7, int a8);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIIIFI(int a0, int a1, int a2, int a3, int a4, float a5, int a6);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIIII(int a0, int a1, int a2, int a3, int a4, int a5);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIIIIF(int a0, int a1, int a2, int a3, int a4, int a5, float a6);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIIIIFFI(int a0, int a1, int a2, int a3, int a4, int a5, float a6, float a7, int a8);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIIIIFI(int a0, int a1, int a2, int a3, int a4, int a5, float a6, int a7);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIIIII(int a0, int a1, int a2, int a3, int a4, int a5, int a6);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIIIIIFI(int a0, int a1, int a2, int a3, int a4, int a5, int a6, float a7, int a8);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIIIIII(int a0, int a1, int a2, int a3, int a4, int a5, int a6, int a7);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIIIIIIII(int a0, int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIIIIIIIIII(int a0, int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIIILL(int a0, int a1, int a2, long a3, long a4);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VIL(int a0, long a1);
        [UnmanagedFunctionPointer(CallingConvention.Cdecl)] internal delegate void VL(long a0);

        /// <summary>Keeps every signature delegate through trimming; the wasm build scans the trimmed assemblies.</summary>
        [DynamicDependency("Invoke", typeof(D))]
        [DynamicDependency("Invoke", typeof(DD))]
        [DynamicDependency("Invoke", typeof(DDD))]
        [DynamicDependency("Invoke", typeof(F))]
        [DynamicDependency("Invoke", typeof(FF))]
        [DynamicDependency("Invoke", typeof(FFF))]
        [DynamicDependency("Invoke", typeof(FFFF))]
        [DynamicDependency("Invoke", typeof(FFFFFF))]
        [DynamicDependency("Invoke", typeof(FFFI))]
        [DynamicDependency("Invoke", typeof(FI))]
        [DynamicDependency("Invoke", typeof(FIF))]
        [DynamicDependency("Invoke", typeof(FIFFFF))]
        [DynamicDependency("Invoke", typeof(FII))]
        [DynamicDependency("Invoke", typeof(FIIF))]
        [DynamicDependency("Invoke", typeof(FIII))]
        [DynamicDependency("Invoke", typeof(I))]
        [DynamicDependency("Invoke", typeof(IF))]
        [DynamicDependency("Invoke", typeof(IFF))]
        [DynamicDependency("Invoke", typeof(IFFFF))]
        [DynamicDependency("Invoke", typeof(II))]
        [DynamicDependency("Invoke", typeof(IIF))]
        [DynamicDependency("Invoke", typeof(IIFF))]
        [DynamicDependency("Invoke", typeof(IIFIIF))]
        [DynamicDependency("Invoke", typeof(IIFIIFI))]
        [DynamicDependency("Invoke", typeof(III))]
        [DynamicDependency("Invoke", typeof(IIIDDII))]
        [DynamicDependency("Invoke", typeof(IIIF))]
        [DynamicDependency("Invoke", typeof(IIIFF))]
        [DynamicDependency("Invoke", typeof(IIIFFFII))]
        [DynamicDependency("Invoke", typeof(IIIFFI))]
        [DynamicDependency("Invoke", typeof(IIIFFII))]
        [DynamicDependency("Invoke", typeof(IIIFII))]
        [DynamicDependency("Invoke", typeof(IIIFIIII))]
        [DynamicDependency("Invoke", typeof(IIII))]
        [DynamicDependency("Invoke", typeof(IIIIFFFIII))]
        [DynamicDependency("Invoke", typeof(IIIIFFII))]
        [DynamicDependency("Invoke", typeof(IIIIFI))]
        [DynamicDependency("Invoke", typeof(IIIIFII))]
        [DynamicDependency("Invoke", typeof(IIIIFIIII))]
        [DynamicDependency("Invoke", typeof(IIIIFIIIII))]
        [DynamicDependency("Invoke", typeof(IIIII))]
        [DynamicDependency("Invoke", typeof(IIIIIF))]
        [DynamicDependency("Invoke", typeof(IIIIIFIIII))]
        [DynamicDependency("Invoke", typeof(IIIIII))]
        [DynamicDependency("Invoke", typeof(IIIIIIF))]
        [DynamicDependency("Invoke", typeof(IIIIIIFFFFI))]
        [DynamicDependency("Invoke", typeof(IIIIIII))]
        [DynamicDependency("Invoke", typeof(IIIIIIII))]
        [DynamicDependency("Invoke", typeof(IIIIIIIIFFI))]
        [DynamicDependency("Invoke", typeof(IIIIIIIII))]
        [DynamicDependency("Invoke", typeof(IIIIIIIIII))]
        [DynamicDependency("Invoke", typeof(IIIIILLI))]
        [DynamicDependency("Invoke", typeof(IIIL))]
        [DynamicDependency("Invoke", typeof(IL))]
        [DynamicDependency("Invoke", typeof(LI))]
        [DynamicDependency("Invoke", typeof(LILLI))]
        [DynamicDependency("Invoke", typeof(LL))]
        [DynamicDependency("Invoke", typeof(V))]
        [DynamicDependency("Invoke", typeof(VF))]
        [DynamicDependency("Invoke", typeof(VFF))]
        [DynamicDependency("Invoke", typeof(VFFFIII))]
        [DynamicDependency("Invoke", typeof(VFFI))]
        [DynamicDependency("Invoke", typeof(VFFII))]
        [DynamicDependency("Invoke", typeof(VFII))]
        [DynamicDependency("Invoke", typeof(VI))]
        [DynamicDependency("Invoke", typeof(VIF))]
        [DynamicDependency("Invoke", typeof(VIFF))]
        [DynamicDependency("Invoke", typeof(VIFFFF))]
        [DynamicDependency("Invoke", typeof(VIFFFIF))]
        [DynamicDependency("Invoke", typeof(VIFFII))]
        [DynamicDependency("Invoke", typeof(VIFI))]
        [DynamicDependency("Invoke", typeof(VIFIIII))]
        [DynamicDependency("Invoke", typeof(VII))]
        [DynamicDependency("Invoke", typeof(VIIF))]
        [DynamicDependency("Invoke", typeof(VIIFF))]
        [DynamicDependency("Invoke", typeof(VIIFFFI))]
        [DynamicDependency("Invoke", typeof(VIIFFFIII))]
        [DynamicDependency("Invoke", typeof(VIIFFFIIIIII))]
        [DynamicDependency("Invoke", typeof(VIIFI))]
        [DynamicDependency("Invoke", typeof(VIIFII))]
        [DynamicDependency("Invoke", typeof(VIIFIIF))]
        [DynamicDependency("Invoke", typeof(VIIFIII))]
        [DynamicDependency("Invoke", typeof(VIIFIIII))]
        [DynamicDependency("Invoke", typeof(VIIFIIIIFI))]
        [DynamicDependency("Invoke", typeof(VIIFIIIIIFI))]
        [DynamicDependency("Invoke", typeof(VIII))]
        [DynamicDependency("Invoke", typeof(VIIIF))]
        [DynamicDependency("Invoke", typeof(VIIIFFF))]
        [DynamicDependency("Invoke", typeof(VIIIFFFI))]
        [DynamicDependency("Invoke", typeof(VIIIFI))]
        [DynamicDependency("Invoke", typeof(VIIIFIII))]
        [DynamicDependency("Invoke", typeof(VIIII))]
        [DynamicDependency("Invoke", typeof(VIIIIF))]
        [DynamicDependency("Invoke", typeof(VIIIIFFI))]
        [DynamicDependency("Invoke", typeof(VIIIIFI))]
        [DynamicDependency("Invoke", typeof(VIIIIFIF))]
        [DynamicDependency("Invoke", typeof(VIIIIFIFI))]
        [DynamicDependency("Invoke", typeof(VIIIII))]
        [DynamicDependency("Invoke", typeof(VIIIIIF))]
        [DynamicDependency("Invoke", typeof(VIIIIIFFII))]
        [DynamicDependency("Invoke", typeof(VIIIIIFI))]
        [DynamicDependency("Invoke", typeof(VIIIIII))]
        [DynamicDependency("Invoke", typeof(VIIIIIIF))]
        [DynamicDependency("Invoke", typeof(VIIIIIIFFI))]
        [DynamicDependency("Invoke", typeof(VIIIIIIFI))]
        [DynamicDependency("Invoke", typeof(VIIIIIII))]
        [DynamicDependency("Invoke", typeof(VIIIIIIIFI))]
        [DynamicDependency("Invoke", typeof(VIIIIIIII))]
        [DynamicDependency("Invoke", typeof(VIIIIIIIIII))]
        [DynamicDependency("Invoke", typeof(VIIIIIIIIIII))]
        [DynamicDependency("Invoke", typeof(VIIILL))]
        [DynamicDependency("Invoke", typeof(VIL))]
        [DynamicDependency("Invoke", typeof(VL))]
        internal static void Keep()
        {
        }
    }
}
#endif
