#!/usr/bin/env bash
# Builds Hexa.NET.ImGui/native/browser-wasm/cimgui.a with the Emscripten on PATH.
#
# The archive is linked into dotnet.wasm by the .NET wasm workload, so Emscripten must match the
# workload's version (3.1.56 for .NET 9 and 10). Objects built by another version can fail to
# link or break at runtime.
#
# The export table (Hexa.NET.ImGui/Browser/cimgui_wasm_exports.c) is generated by the Generator
# (Generator/Targets/WasmTarget.cs) from the binding's function table; this script only compiles it.
set -euo pipefail

CIMGUI_REPO="${CIMGUI_REPO:-https://github.com/JunaMeinhold/cimgui.git}"
# The cimgui commit the checked-in binding (Generator/cimgui) was generated from (Dear ImGui 1.92.9b
# docking); it only adds *_Construct exports the binding does not use.
CIMGUI_REF="${CIMGUI_REF:-576040c4bd36894113d1c1c6ae52c4ffd928cf28}"
FREETYPE_REPO="${FREETYPE_REPO:-https://github.com/freetype/freetype.git}"
FREETYPE_REF="${FREETYPE_REF:-VER-2-13-3}"

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
work="${CIMGUI_WASM_WORK_DIR:-$root/build/cimgui-wasm}"
out="$root/Hexa.NET.ImGui/native/browser-wasm"
exports="$root/Hexa.NET.ImGui/Browser/cimgui_wasm_exports.c"
release_flags=(-DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS_RELEASE="-O3 -DNDEBUG" -DCMAKE_CXX_FLAGS_RELEASE="-O3 -DNDEBUG")

emcc --version | head -n 1

checkout() { # <repo> <ref> <dir>
    if [ ! -d "$3/.git" ]; then
        git clone --quiet "$1" "$3"
    fi
    git -C "$3" fetch --quiet --depth 1 origin "$2" || true
    git -C "$3" checkout --quiet "$2"
}

# FreeType, as on every other platform (the binding is generated with IMGUI_ENABLE_FREETYPE).
# Its bundled zlib is compiled in with internal linkage; libpng, bzip2, brotli and HarfBuzz stay
# off because their libraries would have to be linked into dotnet.wasm too. FreeType uses
# setjmp/longjmp; the .NET runtime links with -fwasm-exceptions, so they must be the wasm kind
# (the default JS kind needs emscripten_longjmp, which dotnet.wasm does not provide).
checkout "$FREETYPE_REPO" "$FREETYPE_REF" "$work/freetype"
emcmake cmake -S "$work/freetype" -B "$work/freetype-build" -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_FLAGS_RELEASE="-O3 -DNDEBUG -fwasm-exceptions -sSUPPORT_LONGJMP=wasm" \
    -DCMAKE_INSTALL_PREFIX="$work/freetype-install" \
    -DBUILD_SHARED_LIBS=OFF \
    -DFT_DISABLE_BZIP2=ON -DFT_DISABLE_PNG=ON -DFT_DISABLE_HARFBUZZ=ON -DFT_DISABLE_BROTLI=ON \
    -DCMAKE_DISABLE_FIND_PACKAGE_ZLIB=ON
cmake --build "$work/freetype-build" --parallel
cmake --install "$work/freetype-build"

checkout "$CIMGUI_REPO" "$CIMGUI_REF" "$work/cimgui"
git -C "$work/cimgui" submodule update --init --recursive --depth 1

emcmake cmake -S "$work/cimgui" -B "$work/build" "${release_flags[@]}" \
    -DIMGUI_STATIC=ON \
    -DIMGUI_WCHAR32=ON \
    -DIMGUI_FREETYPE=ON \
    -Dfreetype_DIR="$work/freetype-install/lib/cmake/freetype" \
    -DCIMGUI_VARGS0=1
cmake --build "$work/build" --parallel

# Same defines as the cimgui target, so cimgui.h declares exactly what the archive defines.
emcc -O3 -DNDEBUG -DIMGUI_USE_WCHAR32 -DCIMGUI_VARGS0 -DIMGUI_ENABLE_FREETYPE -DIMGUI_ENABLE_STB_TRUETYPE \
    -I "$work/cimgui" -c "$exports" -o "$work/cimgui_wasm_exports.o"

# One self-contained archive: cimgui, the export table and FreeType's objects.
mkdir -p "$out" "$work/freetype-objects"
rm -f "$work/freetype-objects"/*.o
(cd "$work/freetype-objects" && emar x "$work/freetype-install/lib/libfreetype.a")
cp "$work/build/cimgui.a" "$out/cimgui.a"
emar rs "$out/cimgui.a" "$work/cimgui_wasm_exports.o" "$work/freetype-objects"/*.o
ls -l "$out/cimgui.a"
